name: CD Front-end

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Railway
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Instalação do cliente Railway
        run: npm install -g --omit=dev @railway/cli
      - name: Build Angular app
        working-directory: sgcmapp/
        run: ng build --configuration=production
      - name: Deploy
        working-directory: sgcmapp/
        run: railway up --detach --service sgcmapp
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

