name: CI Front-end

on:
  push:
    branches:
      - '**'
      - '!main'
    paths:
      - 'sgcmapp/**'
  pull_request:
    paths:
      - 'sgcmapp/**'

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies
        working-directory: sgcmapp/
        run: npm ci
      - name: compilacao
        working-directory: sgcmapp/
        run: ng build
  test:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Dependencies
        working-directory: sgcmapp/
        run: npm ci
      - name: Run Tests
        working-directory: sgcmapp/
        run: ng test --no-watch --no-progress --browsers=ChromeHeadless
  merge:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Merge Branch
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: main
          github_token: ${{ github.token }} 
